oneap:
  event:
    publisher:
      threadPoolSize: 5
      taskIntervalInSeconds: 5
spring:
  datasource:
    url: jdbc:sqlserver://localhost:1433;encrypt=false;
    username: sa
    password: yourStrong(!)Password
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
#  cloud:
#    stream:
#      bindings:
#        consume-in-0:
#          destination: consume
#          group: eventUser
#          consumer:
#            max-attempts: 1
